### ISSUE TITLE
How to build the exe for 32 bit (x86) architecutre?

### ISSUE THREAD

**Issue by shadowwalkersteam** [Kostassoid/lethe#25]
I'm using Intellij and VSCode but I was unable to figure out how to build a 32 bit exe. Can anyone help me in this issue?

**Comment by shadowwalkersteam** [comment]
@Kostassoid Yes it worked.
Can you please also send the command to build for x64? Because now I have both toolchain installed for 32-Bit and 64-Bit so I might need to compile it for both 32 and 64 on the same system. For 32 it is fine just need it for 64-Bit

**Comment by Kostassoid** [comment]
You can use `x86_64-pc-windows-gnu` (or `stable-x86_64-pc-windows-gnu`) toolchain for that, that's what is [used currently](https://github.com/Kostassoid/lethe/blob/master/.travis.yml#L18) in the release pipeline. So the commands should be the same, just replace the toolchain names. But let me know if that doesn't work for some reason.

You can also try `x86_64-pc-windows-msvc` if it fits your running environment better.

**Comment by shadowwalkersteam** [comment]
@Kostassoid Yes it worked. Thanks. The only difference is it was `stable-x86_64-pc-windows-msvc` on my system instead of `stable-x86_64-pc-windows-gnu`

**Comment by shadowwalkersteam** [comment]
@Kostassoid Does Lethe support ARM based Windows Laptops/Tablets?
