### ISSUE TITLE
How to wipe multiple external drives?

### ISSUE THREAD

**Issue by shadowwalkersteam** [Kostassoid/lethe#26]
I've 3-4 external drives connected, When I initiate the wipe on 1 drive it starts wiping and when I start another process of LETHE and try to wipe the other drive it gives error "Unable to enumerate storage devices". How I can use it to wipe multiple drives?
The -l (list) command also doesn't work.
This is the error I get when I try to wipe the other drives if some are already in progress.
Unable to enumerate storage devices. : Cannot open device \\?\Volume{7e6adb17-0000-0000-0000-100000000000}.:

**Comment by Kostassoid** [comment]
That's an interesting case, and a really useful one! I think the behavior is different for Linux and Windows here, on Linux the locked devices would just get skipped and that's how it should be on all platforms. I'll create a fix for that.

**Comment by Kostassoid** [comment]
Hey @shadowwalkersteam
This version should fix the issue you mentioned: https://github.com/Kostassoid/lethe/releases/tag/v0.6.1
Please give it a try.

**Comment by shadowwalkersteam** [comment]
@Kostassoid  Hi, Thanks for the update.
I'll test and update here.

**Comment by Kostassoid** [comment]
@shadowwalkersteam Hey, I'm closing the issue for now, assuming it was fixed. Feel free to reopen if the problem remains.
