### ISSUE TITLE
How can I use this app on the Windows?

### ISSUE THREAD

**Issue by xmha97** [Kostassoid/lethe#34]
How can I use this app on the Windows?
```
C:\Users\Administrator\Downloads\lethe.exe wipe --scheme=zero --blocksize=128k --verify=no E:
```
```
Error: Unknown device E:
```
![image](https://user-images.githubusercontent.com/23485114/192748841-e3ef6cda-10cc-41c2-a4c1-9a1459588e0b.png)

**Comment by Kostassoid** [comment]
Hi @xmha97, 
`E:` is basically a mounting point, the app expects an actual device name (a physical disk or a partition). You can run `lethe.exe list` to find the right device and then you can use a full name or a short ID (to reduce typing).

Saying that, I think it's a valid use case to just use a mounting point like you did. I'll look into that when I have time.

**Comment by xmha97** [comment]
Thanks
