### ISSUE TITLE
How to add customized verification?

### ISSUE THREAD

**Issue by shadowwalkersteam** [Kostassoid/lethe#35]
@Kostassoid  Hi. I want to add a customized verification process, I've introduced new command line argument and the process should be if I send 20 the verification will be completed at 20% instead of 100%. So everytime if I send some number the verification should take place upto that count only not 100%.
Where do I need to make the change? Can you please guide a bit about the class or method where it is appropriate.
Thanks.

**Comment by Kostassoid** [comment]
Hey @shadowwalkersteam,
Interesting idea. Shouldn't be very difficult to implement. I would say the steps are:
1. Add a new field to `WipeTask` struct for defining this limit for verification (in percents, fraction, bytes, etc.). Default should be 100% I assume.
2. Use this new field in `WipeRun::verify` method (simply exit earlier from the while-loop when the limit is reached).
3. Add a command-line arg in `main.rs` and propagate the value into an instance of `WipeTask`.
4. Make sure the UI still makes sense. Update `ConsoleWipeSession` to make sure ETA for verification is adjusted. You have access to an instance of `WipeTask` there so it should be trivial, technically.

I hope this helped.
